// Copyright 2004, Microsoft Corporation
// Sample Code - Use restricted to terms of use defined in the accompanying license agreement (EULA.doc)

//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.4.4.1
// Schema file: HotelRoomInfos.xsd
// Creation Date: 2012-8-31 10:52:06
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace dx177.WebUI.HotelRoomInfos
{

	public struct Declarations
	{
		public const string SchemaVersion = "";
	}


	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class RoomInfoCollection : ArrayList
	{
		public RoomInfo Add(RoomInfo obj)
		{
			base.Add(obj);
			return obj;
		}

		public RoomInfo Add()
		{
			return Add(new RoomInfo());
		}

		public void Insert(int index, RoomInfo obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(RoomInfo obj)
		{
			base.Remove(obj);
		}

		new public RoomInfo this[int index]
		{
			get { return (RoomInfo) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class plansCollection : ArrayList
	{
		public plans Add(plans obj)
		{
			base.Add(obj);
			return obj;
		}

		public plans Add()
		{
			return Add(new plans());
		}

		public void Insert(int index, plans obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(plans obj)
		{
			base.Remove(obj);
		}

		new public plans this[int index]
		{
			get { return (plans) base[index]; }
			set { base[index] = value; }
		}
	}

	[Serializable]
	[EditorBrowsable(EditorBrowsableState.Advanced)]
	public class roomsCollection : ArrayList
	{
		public rooms Add(rooms obj)
		{
			base.Add(obj);
			return obj;
		}

		public rooms Add()
		{
			return Add(new rooms());
		}

		public void Insert(int index, rooms obj)
		{
			base.Insert(index, obj);
		}

		public void Remove(rooms obj)
		{
			base.Remove(obj);
		}

		new public rooms this[int index]
		{
			get { return (rooms) base[index]; }
			set { base[index] = value; }
		}
	}



	[XmlRoot(ElementName="HotelRoomInfos",IsNullable=false),Serializable]
	public class HotelRoomInfos
	{
		[System.Runtime.InteropServices.DispIdAttribute(-4)]
		public IEnumerator GetEnumerator() 
		{
            return RoomInfoCollection.GetEnumerator();
		}

		public RoomInfo Add(RoomInfo obj)
		{
			return RoomInfoCollection.Add(obj);
		}

		[XmlIgnore]
		public RoomInfo this[int index]
		{
			get { return (RoomInfo) RoomInfoCollection[index]; }
		}

		[XmlIgnore]
        public int Count 
		{
            get { return RoomInfoCollection.Count; }
        }

        public void Clear()
		{
			RoomInfoCollection.Clear();
        }

		public RoomInfo Remove(int index) 
		{ 
            RoomInfo obj = RoomInfoCollection[index];
            RoomInfoCollection.Remove(obj);
			return obj;
        }

        public void Remove(object obj)
		{
            RoomInfoCollection.Remove(obj);
        }

		[XmlElement(Type=typeof(RoomInfo),ElementName="RoomInfo",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public RoomInfoCollection __RoomInfoCollection;
		
		[XmlIgnore]
		public RoomInfoCollection RoomInfoCollection
		{
			get
			{
				if (__RoomInfoCollection == null) __RoomInfoCollection = new RoomInfoCollection();
				return __RoomInfoCollection;
			}
			set {__RoomInfoCollection = value;}
		}

		public HotelRoomInfos()
		{
		}
	}


	[XmlType(TypeName="RoomInfo"),Serializable]
	public class RoomInfo
	{

		[XmlElement(ElementName="zid",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __zid;
		
		[XmlIgnore]
		public string zid
		{ 
			get { return __zid; }
			set { __zid = value; }
		}

		[XmlElement(ElementName="eid",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __eid;
		
		[XmlIgnore]
		public string eid
		{ 
			get { return __eid; }
			set { __eid = value; }
		}

		[XmlElement(ElementName="tm1",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="date")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public DateTime __tm1;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __tm1Specified;
		
		[XmlIgnore]
		public DateTime tm1
		{ 
			get { return __tm1; }
			set { __tm1 = value; __tm1Specified = true; }
		}
		
		[XmlIgnore]
		public DateTime tm1Utc
		{ 
			get { return __tm1.ToUniversalTime(); }
			set { __tm1 = value.ToLocalTime(); __tm1Specified = true; }
		}

		[XmlElement(ElementName="tm2",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="date")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public DateTime __tm2;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __tm2Specified;
		
		[XmlIgnore]
		public DateTime tm2
		{ 
			get { return __tm2; }
			set { __tm2 = value; __tm2Specified = true; }
		}
		
		[XmlIgnore]
		public DateTime tm2Utc
		{ 
			get { return __tm2.ToUniversalTime(); }
			set { __tm2 = value.ToLocalTime(); __tm2Specified = true; }
		}

		[XmlElement(ElementName="status",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __status;
		
		[XmlIgnore]
		public string status
		{ 
			get { return __status; }
			set { __status = value; }
		}

		[XmlElement(Type=typeof(rooms),ElementName="rooms",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public roomsCollection __roomsCollection;
		
		[XmlIgnore]
		public roomsCollection roomsCollection
		{
			get
			{
				if (__roomsCollection == null) __roomsCollection = new roomsCollection();
				return __roomsCollection;
			}
			set {__roomsCollection = value;}
		}

		public RoomInfo()
		{
			__tm1 = DateTime.Now;
			__tm2 = DateTime.Now;
		}
	}


	[XmlType(TypeName="rooms"),Serializable]
	public class rooms
	{

		[XmlElement(ElementName="rid",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __rid;
		
		[XmlIgnore]
		public string rid
		{ 
			get { return __rid; }
			set { __rid = value; }
		}

		[XmlElement(ElementName="title",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __title;
		
		[XmlIgnore]
		public string title
		{ 
			get { return __title; }
			set { __title = value; }
		}

		[XmlElement(ElementName="adsl",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __adsl;
		
		[XmlIgnore]
		public string adsl
		{ 
			get { return __adsl; }
			set { __adsl = value; }
		}

		[XmlElement(ElementName="bed",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __bed;
		
		[XmlIgnore]
		public string bed
		{ 
			get { return __bed; }
			set { __bed = value; }
		}

		[XmlElement(ElementName="notes",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __notes;
		
		[XmlIgnore]
		public string notes
		{ 
			get { return __notes; }
			set { __notes = value; }
		}

		[XmlElement(Type=typeof(plans),ElementName="plans",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public plansCollection __plansCollection;
		
		[XmlIgnore]
		public plansCollection plansCollection
		{
			get
			{
				if (__plansCollection == null) __plansCollection = new plansCollection();
				return __plansCollection;
			}
			set {__plansCollection = value;}
		}

		public rooms()
		{
		}
	}


	[XmlType(TypeName="plans"),Serializable]
	public class plans
	{

		[XmlElement(ElementName="planid",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="int")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public int __planid;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __planidSpecified;
		
		[XmlIgnore]
		public int planid
		{ 
			get { return __planid; }
			set { __planid = value; __planidSpecified = true; }
		}

		[XmlElement(ElementName="planname",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __planname;
		
		[XmlIgnore]
		public string planname
		{ 
			get { return __planname; }
			set { __planname = value; }
		}

		[XmlElement(ElementName="totalprice",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="double")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public double __totalprice;
		
		[XmlIgnore]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public bool __totalpriceSpecified;
		
		[XmlIgnore]
		public double totalprice
		{ 
			get { return __totalprice; }
			set { __totalprice = value; __totalpriceSpecified = true; }
		}

		public plans()
		{
		}
	}
}
