// Copyright 2004, Microsoft Corporation
// Sample Code - Use restricted to terms of use defined in the accompanying license agreement (EULA.doc)

//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.4.4.1
// Schema file: HotelInfoImport.xsd
// Creation Date: 2012-8-30 13:50:34
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace dx177.WebUI.HotelInfoImport
{

	public struct Declarations
	{
		public const string SchemaVersion = "";
	}




	[XmlRoot(ElementName="hotelinfo",IsNullable=false),Serializable]
	public class hotelinfo
	{

		[XmlAttribute(AttributeName="HotelName",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __HotelName;
		
		[XmlIgnore]
		public string HotelName
		{ 
			get { return __HotelName; }
			set { __HotelName = value; }
		}

		[XmlElement(Type=typeof(Address),ElementName="Address",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public Address __Address;
		
		[XmlIgnore]
		public Address Address
		{
			get
			{
				if (__Address == null) __Address = new Address();		
				return __Address;
			}
			set {__Address = value;}
		}

		[XmlElement(ElementName="Service",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Service;
		
		[XmlIgnore]
		public string Service
		{ 
			get { return __Service; }
			set { __Service = value; }
		}

		[XmlElement(ElementName="Content",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Content;
		
		[XmlIgnore]
		public string Content
		{ 
			get { return __Content; }
			set { __Content = value; }
		}

		[XmlElement(Type=typeof(Picture),ElementName="Picture",IsNullable=false,Form=XmlSchemaForm.Qualified)]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public Picture __Picture;
		
		[XmlIgnore]
		public Picture Picture
		{
			get
			{
				if (__Picture == null) __Picture = new Picture();		
				return __Picture;
			}
			set {__Picture = value;}
		}

		[XmlElement(ElementName="jianshu",IsNullable=false,Form=XmlSchemaForm.Qualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __jianshu;
		
		[XmlIgnore]
		public string jianshu
		{ 
			get { return __jianshu; }
			set { __jianshu = value; }
		}

		public hotelinfo()
		{
		}
	}


	[XmlType(TypeName="Address"),Serializable]
	public class Address
	{

		[XmlAttribute(AttributeName="v",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __v;
		
		[XmlIgnore]
		public string v
		{ 
			get { return __v; }
			set { __v = value; }
		}

		[XmlText(DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __Value;
		
		[XmlIgnore]
		public string Value
		{ 
			get { return __Value; }
			set { __Value = value; }
		}

		public Address()
		{
		}
	}


	[XmlType(TypeName="Picture"),Serializable]
	public class Picture
	{

		[XmlAttribute(AttributeName="hpicmin",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __hpicmin;
		
		[XmlIgnore]
		public string hpicmin
		{ 
			get { return __hpicmin; }
			set { __hpicmin = value; }
		}

		[XmlAttribute(AttributeName="hpictxt",Form=XmlSchemaForm.Unqualified,DataType="string")]
		[EditorBrowsable(EditorBrowsableState.Advanced)]
		public string __hpictxt;
		
		[XmlIgnore]
		public string hpictxt
		{ 
			get { return __hpictxt; }
			set { __hpictxt = value; }
		}

		public Picture()
		{
		}
	}
}
