#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3634
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionImport
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_MultiArea")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::QuestionImport.Properties.Settings.Default.DB_MultiAreaConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Temp_import_question> Temp_import_question
		{
			get
			{
				return this.GetTable<Temp_import_question>();
			}
		}
	}
	
	[Table(Name="dbo.Temp_import_question")]
	public partial class Temp_import_question
	{
		
		private int _Seqno;
		
		private string _Title;
		
		private string _pContent;
		
		private string _BestReply;
		
		private string _Reply1;
		
		private string _Reply2;
		
		public Temp_import_question()
		{
		}
		
		[Column(Storage="_Seqno", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Seqno
		{
			get
			{
				return this._Seqno;
			}
			set
			{
				if ((this._Seqno != value))
				{
					this._Seqno = value;
				}
			}
		}
		
		[Column(Storage="_Title", DbType="NVarChar(4000) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[Column(Storage="_pContent", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string pContent
		{
			get
			{
				return this._pContent;
			}
			set
			{
				if ((this._pContent != value))
				{
					this._pContent = value;
				}
			}
		}
		
		[Column(Storage="_BestReply", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string BestReply
		{
			get
			{
				return this._BestReply;
			}
			set
			{
				if ((this._BestReply != value))
				{
					this._BestReply = value;
				}
			}
		}
		
		[Column(Storage="_Reply1", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Reply1
		{
			get
			{
				return this._Reply1;
			}
			set
			{
				if ((this._Reply1 != value))
				{
					this._Reply1 = value;
				}
			}
		}
		
		[Column(Storage="_Reply2", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Reply2
		{
			get
			{
				return this._Reply2;
			}
			set
			{
				if ((this._Reply2 != value))
				{
					this._Reply2 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
