// Copyright 2004, Microsoft Corporation
// Sample Code - Use restricted to terms of use defined in the accompanying license agreement (EULA.doc)

//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 1.4.4.1
// Schema file: WeiboTalk.xsd
// Creation Date: 2014-1-22 14:38:56
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;

namespace dx177.Model.WeiboTalk
{

    public struct Declarations
    {
        public const string SchemaVersion = "WeiboTalk";
    }


    [Serializable]
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    public class ItemCollection : ArrayList
    {
        public Item Add(Item obj)
        {
            base.Add(obj);
            return obj;
        }

        public Item Add()
        {
            return Add(new Item());
        }

        public void Insert(int index, Item obj)
        {
            base.Insert(index, obj);
        }

        public void Remove(Item obj)
        {
            base.Remove(obj);
        }

        new public Item this[int index]
        {
            get { return (Item)base[index]; }
            set { base[index] = value; }
        }
    }



    [XmlRoot(ElementName = "WeiboTalkRQ", Namespace = Declarations.SchemaVersion, IsNullable = false), Serializable]
    public class WeiboTalkRQ
    {

        [XmlElement(Type = typeof(Items), ElementName = "Items", IsNullable = false, Form = XmlSchemaForm.Qualified, Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public Items __Items;

        [XmlIgnore]
        public Items Items
        {
            get
            {
                if (__Items == null) __Items = new Items();
                return __Items;
            }
            set { __Items = value; }
        }

        public WeiboTalkRQ()
        {
        }
    }


    [XmlType(TypeName = "Items", Namespace = Declarations.SchemaVersion), Serializable]
    public class Items
    {
        [System.Runtime.InteropServices.DispIdAttribute(-4)]
        public IEnumerator GetEnumerator()
        {
            return ItemCollection.GetEnumerator();
        }

        public Item Add(Item obj)
        {
            return ItemCollection.Add(obj);
        }

        [XmlIgnore]
        public Item this[int index]
        {
            get { return (Item)ItemCollection[index]; }
        }

        [XmlIgnore]
        public int Count
        {
            get { return ItemCollection.Count; }
        }

        public void Clear()
        {
            ItemCollection.Clear();
        }

        public Item Remove(int index)
        {
            Item obj = ItemCollection[index];
            ItemCollection.Remove(obj);
            return obj;
        }

        public void Remove(object obj)
        {
            ItemCollection.Remove(obj);
        }

        [XmlElement(Type = typeof(Item), ElementName = "Item", IsNullable = false, Form = XmlSchemaForm.Qualified, Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public ItemCollection __ItemCollection;

        [XmlIgnore]
        public ItemCollection ItemCollection
        {
            get
            {
                if (__ItemCollection == null) __ItemCollection = new ItemCollection();
                return __ItemCollection;
            }
            set { __ItemCollection = value; }
        }

        public Items()
        {
        }
    }


    [XmlType(TypeName = "Item", Namespace = Declarations.SchemaVersion), Serializable]
    public class Item
    {

        [XmlElement(ElementName = "JingQuCode", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __JingQuCode;

        [XmlIgnore]
        public string JingQuCode
        {
            get { return __JingQuCode; }
            set { __JingQuCode = value; }
        }

        [XmlElement(ElementName = "CreateTime", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "dateTime", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public DateTime __CreateTime;

        [XmlIgnore]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public bool __CreateTimeSpecified;

        [XmlIgnore]
        public DateTime CreateTime
        {
            get { return __CreateTime; }
            set { __CreateTime = value; __CreateTimeSpecified = true; }
        }

        [XmlIgnore]
        public DateTime CreateTimeUtc
        {
            get { return __CreateTime.ToUniversalTime(); }
            set { __CreateTime = value.ToLocalTime(); __CreateTimeSpecified = true; }
        }

        [XmlElement(ElementName = "Guid", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __Guid;

        [XmlIgnore]
        public string Guid
        {
            get { return __Guid; }
            set { __Guid = value; }
        }

        [XmlElement(ElementName = "Talk", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __Talk;

        [XmlIgnore]
        public string Talk
        {
            get { return __Talk; }
            set { __Talk = value; }
        }

        [XmlElement(ElementName = "Keyval", IsNullable = false, Form = XmlSchemaForm.Qualified, DataType = "string", Namespace = Declarations.SchemaVersion)]
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public string __Keyval;

        [XmlIgnore]
        public string Keyval
        {
            get { return __Keyval; }
            set { __Keyval = value; }
        }

        public Item()
        {
            __CreateTime = DateTime.Now;
        }
    }
}
